server:
  servlet:
    context-path: /aai
  port: 9872

spring:
  jpa:
    generate-ddl: false
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/aai
    username: aai
    password: aai
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
