server:
  servlet:
    context-path: /aai
  port: 9872

spring:
  jpa:
    generate-ddl: false
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
