delete from doctorInsurance;
delete from doctorSpeciality;
delete from insurance;
delete from specialitysynonyme;
delete from speciality;
delete from doctor;
delete from pharmacy;
delete from hours;
delete from facility;
